version: '3'
services:
  nginx-server:
    build: 
      context: ./nginx_server
      dockerfile: Dockerfile
    container_name: nginx_server
    restart:  unless-stopped
    expose:
      - 80
    ports:
      - "80:80"
    networks:
      - lab-net
  apache-server:
    build: 
      context: ./apache_server
      dockerfile: Dockerfile
    container_name: apache_server
    restart: always
    expose:
      - 80
    ports:
      - "8080:80"
    networks:
      - lab-net
  compose-server:
    image: docker/compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab-net
  
networks:
  lab-net:
    driver: bridge


