version: '3'
services:
  nginx_server:
    build: 
      context: ./nginx_server
      dockerfile: Dockerfile
    container_name: nginx_server
    restart:  unless-stopped
    expose:
      - 80
    ports:
      - "80:80"
    networks:
      - lab-net
  apache_server:
    build: 
      context: ./apache_server
      dockerfile: Dockerfile
    container_name: apache_server
    restart: always
    expose:
      - 80
    ports:
      - "8080:80"
    networks:
      - lab-net
  compose_server:
    image: docker/compose:latest
    container_name: compose_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab-net
  
networks:
  lab-net:
    driver: bridge


